WHENEVER SQLERROR EXIT SQL.SQLCODE;

CREATE TABLE "NMMR"."ACUMULAMONTOCD"
(
    "ID_ACUMULAMONTOCD" NUMBER(10,0),
    "ID_CANAL" NUMBER(3,0),
    "ID_DISPOSITIVO" NUMBER(3,0),
    "ID_TIPO_DOCUMENTO" NUMBER(3,0),
    "NUM_DOCUMENTO" VARCHAR2(12 BYTE),
    "MONTO_TOTAL" NUMBER(15,5),
    "ESTADO" CHAR(1 BYTE),
    "USUARIO_CREACION" VARCHAR2(30 BYTE),
    "FECHA_CREACION" DATE,
    "USUARIO_MODIFICACION" VARCHAR2(30 BYTE),
    "FECHA_MODIFICACION" DATE
);

EXIT SUCCESS;
